{% set name = "suitcase-json-metadata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 722e6a0d89a94fe3ff55717ce73eeffadf5226d4dfc0998d4e739f67f39c4dd5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - event-model >=1.8.0
    - suitcase-utils

test:
  imports:
    - suitcase.json_metadata
    - suitcase.json_metadata.tests

about:
  home: https://blueskyproject.io/suitcase
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents' metadata to JSON
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-json-metadata

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
